/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package componente;
//Imports necesarios para que funcione
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author rober
 */
public class Captcha extends javax.swing.JFrame {

    /**
     * Creates new form Captcha
     */
    public Captcha() {
        initComponents();
        //this.setLocationRelativeTo es para que la ventana aparezca en medio de la pantalla
        this.setLocationRelativeTo(this);
        //Aqui es donde se insertan las imagenes, especificas el label al que quieres insertar e ingresas la ruta de tu imagen 
        setImageLabel(lbl1,"C:/Users/rober/OneDrive/Escritorio/moto1.jpg");
        setImageLabel(lbl6,"C:/Users/rober/OneDrive/Escritorio/moto2.png");
        setImageLabel(lbl9,"C:/Users/rober/OneDrive/Escritorio/moto3.jpg");
        setImageLabel(lbl7,"C:/Users/rober/OneDrive/Escritorio/moto4.jpg");
        setImageLabel(lbl2,"C:/Users/rober/OneDrive/Escritorio/sinMoto1.jpg");
        setImageLabel(lbl3,"C:/Users/rober/OneDrive/Escritorio/sinMoto2.png");
        setImageLabel(lbl4,"C:/Users/rober/OneDrive/Escritorio/sinMoto3.png");
         setImageLabel(lbl8,"C:/Users/rober/OneDrive/Escritorio/sinMoto4.png");
        setImageLabel(lbl5,"C:/Users/rober/OneDrive/Escritorio/sinMoto5.jfif");
    }

    
    //Este metodo es para insertar las imagenes al Label y autoajustarlas a su tamaño
    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(),Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    //Este metodo es para cambiar el fondo de seleccion, por defecto es gris 
    /* private void toggleButtonEffect(JToggleButton button) {
        if (button.isSelected()) {
            button.setBackground(Color.lightGray); // Cambiar el fondo al seleccionar
        } else {
            button.setBackground(null); // Restaurar el fondo al deseleccionar
        }
    }
    */
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        button1 = new javax.swing.JToggleButton();
        lbl2 = new javax.swing.JLabel();
        button2 = new javax.swing.JToggleButton();
        lbl3 = new javax.swing.JLabel();
        button3 = new javax.swing.JToggleButton();
        lbl4 = new javax.swing.JLabel();
        button4 = new javax.swing.JToggleButton();
        lbl5 = new javax.swing.JLabel();
        button5 = new javax.swing.JToggleButton();
        lbl6 = new javax.swing.JLabel();
        button6 = new javax.swing.JToggleButton();
        lbl7 = new javax.swing.JLabel();
        button7 = new javax.swing.JToggleButton();
        lbl8 = new javax.swing.JLabel();
        button8 = new javax.swing.JToggleButton();
        lbl9 = new javax.swing.JLabel();
        button9 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        buttonInfo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAPTCHA DE VERIFICACION");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("contengan motocicletas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 380, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selecciona todas las imagenes que");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 480, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoazulito.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 147, 255)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 500, 100));

        lbl1.setText("jLabel4");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 140));

        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 160));

        lbl2.setText("jLabel4");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 140));

        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, 160));

        lbl3.setText("jLabel4");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 140, 140));

        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 160, 160));

        lbl4.setText("jLabel4");
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 140));

        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 160));

        lbl5.setText("jLabel4");
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 140, 140));

        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 160, 160));

        lbl6.setText("jLabel4");
        getContentPane().add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 140, 140));

        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 160, 160));

        lbl7.setText("jLabel4");
        getContentPane().add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 140, 140));

        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 160, 160));

        lbl8.setText("jLabel4");
        getContentPane().add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 140, 140));

        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 160, 160));

        lbl9.setText("jLabel4");
        getContentPane().add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 140, 140));

        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 160, 160));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VERIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 130, 50));

        buttonInfo.setBackground(java.awt.SystemColor.controlHighlight);
        buttonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        buttonInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonInfoMouseClicked(evt);
            }
        });
        buttonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 60, 50));

        jButton3.setBackground(java.awt.SystemColor.controlHighlight);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/refrescar_1.png"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 60, 50));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 500, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button8ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed
        //Este metodo determina si fueron elegidas correctamente las imagenes, son 4 las correctas pero dependen de la posicion en las que las ingresaste
        //si el button1 tiene un label con imagen de moto, entonces la seleccion es correcta 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int correctSelections = 0;
    if (button1.isSelected()) correctSelections++;
    if (button6.isSelected()) correctSelections++;
    if (button7.isSelected()) correctSelections++;
    if (button9.isSelected()) correctSelections++;
    if (correctSelections == 4) { // Adjust the threshold as needed
        JOptionPane.showMessageDialog(null, "¡Felicidades, no eres un robot!");
        dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Vuelve a intentarlo");
    }
    }//GEN-LAST:event_jButton1ActionPerformed
        //Aqui lo unico que hice fue asociarle otra ventana al seleccionar el boton de informacion (i)
    private void buttonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoActionPerformed
    Informacion info = new Informacion();
    info.setVisible(true);
    }//GEN-LAST:event_buttonInfoActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
       
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        
    }//GEN-LAST:event_button4ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
      
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
       
    }//GEN-LAST:event_button7ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
      
    }//GEN-LAST:event_button9ActionPerformed

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked

    }//GEN-LAST:event_button2MouseClicked

    private void buttonInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonInfoMouseClicked
        
    }//GEN-LAST:event_buttonInfoMouseClicked
                
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Captcha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Captcha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Captcha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Captcha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Captcha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton button1;
    private javax.swing.JToggleButton button2;
    private javax.swing.JToggleButton button3;
    private javax.swing.JToggleButton button4;
    private javax.swing.JToggleButton button5;
    private javax.swing.JToggleButton button6;
    private javax.swing.JToggleButton button7;
    private javax.swing.JToggleButton button8;
    private javax.swing.JToggleButton button9;
    private javax.swing.JButton buttonInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    // End of variables declaration//GEN-END:variables
}
